set_property PACKAGE_PIN W4 [get_ports {anode[3]}]
set_property PACKAGE_PIN V4 [get_ports {anode[2]}]
set_property PACKAGE_PIN U4 [get_ports {anode[1]}]
set_property PACKAGE_PIN U2 [get_ports {anode[0]}]
set_property PACKAGE_PIN W7 [get_ports {cathode[6]}]
set_property PACKAGE_PIN W6 [get_ports {cathode[5]}]
set_property PACKAGE_PIN U8 [get_ports {cathode[4]}]
set_property PACKAGE_PIN V8 [get_ports {cathode[3]}]
set_property PACKAGE_PIN U5 [get_ports {cathode[2]}]
set_property PACKAGE_PIN V5 [get_ports {cathode[1]}]
set_property PACKAGE_PIN U7 [get_ports {cathode[0]}]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports {cathode[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cathode[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cathode[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cathode[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cathode[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cathode[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cathode[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {anode[0]}]


set_property PACKAGE_PIN W17 [get_ports {num[3]}]
set_property PACKAGE_PIN W16 [get_ports {num[2]}]
set_property PACKAGE_PIN V16 [get_ports {num[1]}]
set_property PACKAGE_PIN V17 [get_ports {num[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {num[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {num[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {num[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {num[0]}]
set_property PACKAGE_PIN T18 [get_ports equal]
set_property PACKAGE_PIN U16 [get_ports overflow]
set_property IOSTANDARD LVCMOS33 [get_ports equal]
set_property IOSTANDARD LVCMOS33 [get_ports overflow]


set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets equal_IBUF]


set_property IOSTANDARD LVCMOS33 [get_ports control]
set_property PACKAGE_PIN R2 [get_ports control]
