set_property IOSTANDARD LVCMOS33 [get_ports {cs[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cs[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {cs[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {row[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {row[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {row[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {row[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SSD[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SSD[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SSD[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SSD[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SSD[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SSD[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SSD[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SSD[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SSD[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SSD[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {SSD[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports Reset]
set_property PACKAGE_PIN W5 [get_ports clk]
set_property PACKAGE_PIN W19 [get_ports Reset]
set_property PACKAGE_PIN W4 [get_ports {SSD[10]}]
set_property PACKAGE_PIN V4 [get_ports {SSD[9]}]
set_property PACKAGE_PIN U4 [get_ports {SSD[8]}]
set_property PACKAGE_PIN U2 [get_ports {SSD[7]}]
set_property PACKAGE_PIN W7 [get_ports {SSD[6]}]
set_property PACKAGE_PIN W6 [get_ports {SSD[5]}]
set_property PACKAGE_PIN U8 [get_ports {SSD[4]}]
set_property PACKAGE_PIN V8 [get_ports {SSD[3]}]
set_property PACKAGE_PIN U5 [get_ports {SSD[2]}]
set_property PACKAGE_PIN V5 [get_ports {SSD[1]}]
set_property PACKAGE_PIN U7 [get_ports {SSD[0]}]
set_property PACKAGE_PIN U19 [get_ports {cs[2]}]
set_property PACKAGE_PIN E19 [get_ports {cs[1]}]
set_property PACKAGE_PIN U16 [get_ports {cs[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {col_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {col_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {col_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {col_out[0]}]
set_property PACKAGE_PIN A14 [get_ports {col_out[3]}]
set_property PACKAGE_PIN B15 [get_ports {col_out[1]}]
set_property PACKAGE_PIN P18 [get_ports {row[3]}]
set_property PACKAGE_PIN N17 [get_ports {row[2]}]
set_property PACKAGE_PIN M18 [get_ports {row[1]}]
set_property PACKAGE_PIN K17 [get_ports {row[0]}]

set_property PACKAGE_PIN B16 [get_ports {col_out[0]}]
set_property PACKAGE_PIN A16 [get_ports {col_out[2]}]


set_property IOSTANDARD LVCMOS33 [get_ports OR_row]



set_property PACKAGE_PIN L1 [get_ports {col[3]}]
set_property PACKAGE_PIN P1 [get_ports {col[2]}]
set_property PACKAGE_PIN N3 [get_ports {col[1]}]
set_property PACKAGE_PIN P3 [get_ports {col[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {col[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {col[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {col[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {col[0]}]
set_property PACKAGE_PIN U3 [get_ports {row_out[3]}]
set_property PACKAGE_PIN W3 [get_ports {row_out[2]}]
set_property PACKAGE_PIN V3 [get_ports {row_out[1]}]
set_property PACKAGE_PIN V13 [get_ports {row_out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {row_out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {row_out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {row_out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {row_out[0]}]

set_property PACKAGE_PIN V14 [get_ports {col_o[2]}]
set_property PACKAGE_PIN U14 [get_ports {col_o[1]}]
set_property PACKAGE_PIN U15 [get_ports {col_o[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {col_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {col_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {col_o[0]}]
set_property PACKAGE_PIN W18 [get_ports OR_row]
